### ISSUE TITLE
Tracking issue: Release a new cage

### ISSUE THREAD

**Issue by emk** [faradayio/cage#76]
We have a number of `cage` patches that people would like to have merged and released soon. These include:

- [x] We need to make sure that cage builds without errors. Any takers?
- [x] #74: `--no-deps`. Needs confirmation from @dkastner.
- [x] #70: Strip `build` except when needed. Requires final fixup from @camjackson, merge from @emk.
- [x] #75: Needs a PR updating `Cargo.toml` to use the new `compose_yml` release (0.0.49?). @camjackson, are you interested?
- [x] ~~#78 Fix beta build (waiting to see [if Travis is green](https://github.com/faradayio/cage/commits/master))~~

**Comment by camjackson** [comment]
Yep, I'll bump the `compose_yml` version. I'll make sure there are no build errors along the way - is that what the first item refers to?

**Comment by camjackson** [comment]
PR is ready for the compose upgrade.

WRT cage building without errors, looking at the Travis logs for my PR:
- Stable Linux seems like a clean build, other than the rustfmt diff.
- Stable MacOS is mostly a clean build, except for these lines right at the end:

    ```
    changes detected, packing new archive
    .
    <Cut several lines of ...>
    .
    running `casher push` took longer than 180 seconds and has been aborted

    Done. Your build exited with 0.
    /Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
    ```
- Beta Linux is taking a long time to run, but it looks like it might pass?
- Nightly Linux is failing with a whole bunch of clippy errors.

**Comment by emk** [comment]
We're getting close. Mostly, I'm just blocked on the code review for #70 and figuring out what's broken on CI.

**Comment by camjackson** [comment]
Would it help if I rebased that branch onto master?

**Comment by emk** [comment]
OK, we're getting really close. I'm waiting on a revised PR for #70 from @camjackson, and to see if I've fixed `cargo new` as described in #78.

**Comment by emk** [comment]
OK, we've addressed everything we can here, and I've moved the build issue #78 to the 0.2.4 milestone. Thank you to everybody who helped!
